---
- hosts: test
  remote_user: ubuntu
  tasks:
    - name: setup jr user
      user:
        name: jr
        comment: Jonathan Riddell
        groups: sudo
        password: "{{ pass }}"
        shell: /bin/bash
      become: yes
